import Head from 'next/head'
import { styles } from '@/styles/styles' // styles.paddingX idhar sai ai hai
import Navbar from '@/components/Navbar'
import Hero from '@/components/Hero'

export default function Home() {
  return (
    <>
      <Head>
        <title>Jrbi - Psychologist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className="bg-hero-pattern bg-cover bg-no-repeat bg-center z-0">
        <Navbar/>
        <Hero/>
      </div>
      </main>
    </>
  )
}
