import Head from "next/head";
// import { styles } from "@/styles/styles"; // styles.paddingX idhar sai ai hai
import Hero from "@/components/Hero";
import Service from "@/components/Service";
import Interversions from "@/components/Interversions";
import Blog from "@/components/Blog";
import Contact from "@/components/Contact"
import { createClient } from "next-sanity";
import Whocanjoin from "@/components/Whocanjoin";
import Video from "@/components/Video";
export default function Home({posts,author,youtube}) {
  const firstThreePosts = posts.slice(0, 3);
  return (
    <>
      <Head>
        <title>Jrbi - Psychologist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div class="relative overflow-x-hidden prose-h2:text-6xl prose-h1:text-8xl prose-h3:text-tertiary ">
          <div class="absolute w-[380px] -top-36 right-20 min-h-screen bg-hero-pattern bg-contain bg-no-repeat bg-right-bottom opacity-10 overflow-hidden z-0 " />
          <Hero />
          <Service />
          <Whocanjoin/>
          <Interversions/>
          <h2 className='font-anton text-5xl flex justify-center items-center mx-auto text-tertiary py-4'>Popular Blog</h2>
          <Blog posts={firstThreePosts}/>
          <Video youtube={youtube}/>
          <Contact/>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const client = createClient({
    projectId: "rpf7v2k6", //Project id is in the sanity.json
    dataset: "production",
    useCdn: false,
  });
  const posts = await client.fetch(`*[_type == "blog"]`);
  const author = await client.fetch(`*[_type == "author"]`);
  const youtube = await client.fetch(`*[_type == "youtube"]`);
  return {
    props: {
      posts, //Return the fetch variable
      author,
      youtube
    },
  };
}